# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
  
- task: Npm@1
  inputs:
    command: 'install'
    verbose: true
    customRegistry: 'useFeed'
    customFeed: 'd9ecb648-bec3-489a-8033-491efc9722a1/68378af9-2d8c-48bf-b1c8-9a01f4ad4851'
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Run Build'

- script: |
    npm test
  displayName: 'Run Tests'