# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
  
- task: Npm@1
  inputs:
    command: 'install'
    verbose: true
    customRegistry: 'useFeed'
    customFeed: '7f3e8d94-c48d-41cc-b5aa-0aee0596a809/2ad29166-69b2-465e-b7d8-6b9d66443d60'
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Run Build'

- script: |
    npm test
  displayName: 'Run Tests'